grpc:
  server:
    port: 9444


management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://13.210.238.162:4318/v1/metrics
        step: 10s

    tracing:
      endpoint: http://13.210.238.162:4318/v1/traces
  log:
    exporter:
      endpoint: http://13.210.238.162:4317

  tracing:
    sampling:
      probability: 1
spring:
  application:
    name: auth
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: maivanminh.se@gmail.com
    password: bvcx tsfj tbgi ifzz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ap-east-1.8ada6794-d1df-4c6b-99c0-4799c810b909.aws.yugabyte.cloud:5433/postgres
    username: admin
    password: Software-2025
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  threads:
    virtual:
      enabled: true

application:
  security:
    jwt:
      secret-key: $2a$12$iP3.JTboJiEaRDe3lLx4oOkZbBCf8Yf.7SO8UR8D8g2NWvNL3m0nu
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days