receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: prometheus

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    logs:
      receivers: [otlp]
      exporters: [loki]
