spring:
  application:
    name: core
grpc:
  server:
    port: 9443

management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://13.210.238.162:4318/v1/metrics
        step: 10s

    tracing:
      endpoint: http://13.210.238.162:4318/v1/traces
  log:
    exporter:
      endpoint: http://13.210.238.162:4317

  tracing:
    sampling:
      probability: 1
