spring:
  application:
    name: core
  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:postgresql://pg-123-software-archietecture.g.aivencloud.com:24304/defaultdb
    username: avnadmin
    password: AVNS_wHto-Oo314q58y0n5fr
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000


    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialec

grpc:
  server:
    port: 9443

management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://13.210.238.162:4318/v1/metrics
        step: 10s

    tracing:
      endpoint: http://13.210.238.162:4318/v1/traces
  log:
    exporter:
      endpoint: http://13.210.238.162:4317

  tracing:
    sampling:
      probability: 1
