server:
  port: 8080
grpc:
  client:
    coreService:
      address: static://localhost:9443
      negotiation-type: plaintext
    authService:
      address: static://localhost:9444
      negotiation-type: plaintext

management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s

    tracing:
      endpoint: http://localhost:4318/v1/traces

  tracing:
    sampling:
      probability: 1