server:
  port: 8080
grpc:
  client:
    coreService:
      address: localhost:9443
      negotiation-type: plaintext
    authService:
      address: localhost:9444
      negotiation-type: plaintext
    verifyTokenService:
      address: localhost:9444
      negotiation-type: plaintext

    registerService:
      address: localhost:9444
      negotiation-type: plaintext

    loginService:
      address: localhost:9444
      negotiation-type: plaintext

    logoutService:
      address: localhost:9444
      negotiation-type: plaintext

    refreshTokenService:
      address: localhost:9444
      negotiation-type: plaintext

    verifyEmailService:
      address: localhost:9444
      negotiation-type: plaintext


management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s

    tracing:
      endpoint: http://localhost:4318/v1/traces

  tracing:
    sampling:
      probability: 1