spring:
  application:
    name: bff
  rabbitmq:
    host: 13.210.238.162
    port: 5672
    username: admin
    password: admin

server:
  port: 8080
grpc:
  client:
    coreService:
      address: ${GRPC_CLIENT_CORE_ADDRESS:localhost:9443}
      negotiation-type: plaintext
    authService:
      address: ${GRPC_CLIENT_AUTH_ADDRESS:localhost:9444}
      negotiation-type: plaintext

management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://13.210.238.162:4318/v1/metrics
        step: 10s

    tracing:
      endpoint: http://13.210.238.162:4318/v1/traces
  log:
    exporter:
      endpoint: http://13.210.238.162:4317

  tracing:
    sampling:
      probability: 1