// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package org.archi.common.auth;

public interface GetBrandsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetBrandsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>.google.protobuf.StringValue sort = 3;</code>
   * @return Whether the sort field is set.
   */
  boolean hasSort();
  /**
   * <code>.google.protobuf.StringValue sort = 3;</code>
   * @return The sort.
   */
  com.google.protobuf.StringValue getSort();
  /**
   * <code>.google.protobuf.StringValue sort = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getSortOrBuilder();

  /**
   * <code>.google.protobuf.StringValue name = 4;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 4;</code>
   * @return The name.
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();
}
