// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package org.archi.common.auth;

public interface GetBrandsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetBrandsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>optional string sort = 3;</code>
   * @return Whether the sort field is set.
   */
  boolean hasSort();
  /**
   * <code>optional string sort = 3;</code>
   * @return The sort.
   */
  java.lang.String getSort();
  /**
   * <code>optional string sort = 3;</code>
   * @return The bytes for sort.
   */
  com.google.protobuf.ByteString
      getSortBytes();

  /**
   * <code>optional string name = 4;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
