// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package org.archi.common.auth;

public interface PlayerProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlayerProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Account ID.
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
