// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package org.archi.common.notification;

public interface PostSendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostSendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 senderId = 1;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <code>int64 recipientId = 2;</code>
   * @return The recipientId.
   */
  long getRecipientId();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
