// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

/**
 * Protobuf type {@code AddGamePlayerResponse}
 */
public final class AddGamePlayerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AddGamePlayerResponse)
    AddGamePlayerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddGamePlayerResponse.newBuilder() to construct.
  private AddGamePlayerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddGamePlayerResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddGamePlayerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.archi.common.core.CoreProto.internal_static_AddGamePlayerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.archi.common.core.CoreProto.internal_static_AddGamePlayerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.archi.common.core.AddGamePlayerResponse.class, org.archi.common.core.AddGamePlayerResponse.Builder.class);
  }

  public static final int GAMEPLAYER_FIELD_NUMBER = 1;
  private org.archi.common.core.GamePlayer gamePlayer_;
  /**
   * <code>.GamePlayer gamePlayer = 1;</code>
   * @return Whether the gamePlayer field is set.
   */
  @java.lang.Override
  public boolean hasGamePlayer() {
    return gamePlayer_ != null;
  }
  /**
   * <code>.GamePlayer gamePlayer = 1;</code>
   * @return The gamePlayer.
   */
  @java.lang.Override
  public org.archi.common.core.GamePlayer getGamePlayer() {
    return gamePlayer_ == null ? org.archi.common.core.GamePlayer.getDefaultInstance() : gamePlayer_;
  }
  /**
   * <code>.GamePlayer gamePlayer = 1;</code>
   */
  @java.lang.Override
  public org.archi.common.core.GamePlayerOrBuilder getGamePlayerOrBuilder() {
    return getGamePlayer();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (gamePlayer_ != null) {
      output.writeMessage(1, getGamePlayer());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (gamePlayer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGamePlayer());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.archi.common.core.AddGamePlayerResponse)) {
      return super.equals(obj);
    }
    org.archi.common.core.AddGamePlayerResponse other = (org.archi.common.core.AddGamePlayerResponse) obj;

    if (hasGamePlayer() != other.hasGamePlayer()) return false;
    if (hasGamePlayer()) {
      if (!getGamePlayer()
          .equals(other.getGamePlayer())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGamePlayer()) {
      hash = (37 * hash) + GAMEPLAYER_FIELD_NUMBER;
      hash = (53 * hash) + getGamePlayer().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.archi.common.core.AddGamePlayerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.archi.common.core.AddGamePlayerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AddGamePlayerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AddGamePlayerResponse)
      org.archi.common.core.AddGamePlayerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.archi.common.core.CoreProto.internal_static_AddGamePlayerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.archi.common.core.CoreProto.internal_static_AddGamePlayerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.archi.common.core.AddGamePlayerResponse.class, org.archi.common.core.AddGamePlayerResponse.Builder.class);
    }

    // Construct using org.archi.common.core.AddGamePlayerResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (gamePlayerBuilder_ == null) {
        gamePlayer_ = null;
      } else {
        gamePlayer_ = null;
        gamePlayerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.archi.common.core.CoreProto.internal_static_AddGamePlayerResponse_descriptor;
    }

    @java.lang.Override
    public org.archi.common.core.AddGamePlayerResponse getDefaultInstanceForType() {
      return org.archi.common.core.AddGamePlayerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.archi.common.core.AddGamePlayerResponse build() {
      org.archi.common.core.AddGamePlayerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.archi.common.core.AddGamePlayerResponse buildPartial() {
      org.archi.common.core.AddGamePlayerResponse result = new org.archi.common.core.AddGamePlayerResponse(this);
      if (gamePlayerBuilder_ == null) {
        result.gamePlayer_ = gamePlayer_;
      } else {
        result.gamePlayer_ = gamePlayerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.archi.common.core.AddGamePlayerResponse) {
        return mergeFrom((org.archi.common.core.AddGamePlayerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.archi.common.core.AddGamePlayerResponse other) {
      if (other == org.archi.common.core.AddGamePlayerResponse.getDefaultInstance()) return this;
      if (other.hasGamePlayer()) {
        mergeGamePlayer(other.getGamePlayer());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getGamePlayerFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private org.archi.common.core.GamePlayer gamePlayer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.archi.common.core.GamePlayer, org.archi.common.core.GamePlayer.Builder, org.archi.common.core.GamePlayerOrBuilder> gamePlayerBuilder_;
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     * @return Whether the gamePlayer field is set.
     */
    public boolean hasGamePlayer() {
      return gamePlayerBuilder_ != null || gamePlayer_ != null;
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     * @return The gamePlayer.
     */
    public org.archi.common.core.GamePlayer getGamePlayer() {
      if (gamePlayerBuilder_ == null) {
        return gamePlayer_ == null ? org.archi.common.core.GamePlayer.getDefaultInstance() : gamePlayer_;
      } else {
        return gamePlayerBuilder_.getMessage();
      }
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     */
    public Builder setGamePlayer(org.archi.common.core.GamePlayer value) {
      if (gamePlayerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gamePlayer_ = value;
        onChanged();
      } else {
        gamePlayerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     */
    public Builder setGamePlayer(
        org.archi.common.core.GamePlayer.Builder builderForValue) {
      if (gamePlayerBuilder_ == null) {
        gamePlayer_ = builderForValue.build();
        onChanged();
      } else {
        gamePlayerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     */
    public Builder mergeGamePlayer(org.archi.common.core.GamePlayer value) {
      if (gamePlayerBuilder_ == null) {
        if (gamePlayer_ != null) {
          gamePlayer_ =
            org.archi.common.core.GamePlayer.newBuilder(gamePlayer_).mergeFrom(value).buildPartial();
        } else {
          gamePlayer_ = value;
        }
        onChanged();
      } else {
        gamePlayerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     */
    public Builder clearGamePlayer() {
      if (gamePlayerBuilder_ == null) {
        gamePlayer_ = null;
        onChanged();
      } else {
        gamePlayer_ = null;
        gamePlayerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     */
    public org.archi.common.core.GamePlayer.Builder getGamePlayerBuilder() {
      
      onChanged();
      return getGamePlayerFieldBuilder().getBuilder();
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     */
    public org.archi.common.core.GamePlayerOrBuilder getGamePlayerOrBuilder() {
      if (gamePlayerBuilder_ != null) {
        return gamePlayerBuilder_.getMessageOrBuilder();
      } else {
        return gamePlayer_ == null ?
            org.archi.common.core.GamePlayer.getDefaultInstance() : gamePlayer_;
      }
    }
    /**
     * <code>.GamePlayer gamePlayer = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.archi.common.core.GamePlayer, org.archi.common.core.GamePlayer.Builder, org.archi.common.core.GamePlayerOrBuilder> 
        getGamePlayerFieldBuilder() {
      if (gamePlayerBuilder_ == null) {
        gamePlayerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.archi.common.core.GamePlayer, org.archi.common.core.GamePlayer.Builder, org.archi.common.core.GamePlayerOrBuilder>(
                getGamePlayer(),
                getParentForChildren(),
                isClean());
        gamePlayer_ = null;
      }
      return gamePlayerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AddGamePlayerResponse)
  }

  // @@protoc_insertion_point(class_scope:AddGamePlayerResponse)
  private static final org.archi.common.core.AddGamePlayerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.archi.common.core.AddGamePlayerResponse();
  }

  public static org.archi.common.core.AddGamePlayerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddGamePlayerResponse>
      PARSER = new com.google.protobuf.AbstractParser<AddGamePlayerResponse>() {
    @java.lang.Override
    public AddGamePlayerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddGamePlayerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddGamePlayerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.archi.common.core.AddGamePlayerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

