// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

public final class CoreProto {
  private CoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVoucherTypesReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVoucherTypesReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVoucherTypesRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVoucherTypesRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVouchersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVouchersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVouchersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVouchersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchVoucherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchVoucherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchVoucherTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchVoucherTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Voucher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Voucher_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateVoucherTypeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateVoucherTypeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateVoucherTypeRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateVoucherTypeRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateVoucherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateVoucherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateVoucherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateVoucherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateVoucherTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateVoucherTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateVoucherTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateVoucherTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoucherType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoucherType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Campaign_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Campaign_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchCampaignRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchCampaignRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchCampaignResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchCampaignResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateCampaignRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateCampaignRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateCampaignResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateCampaignResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsByBrandIdReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsByBrandIdReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsByBrandIdRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsByBrandIdRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateCampaignReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateCampaignReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateCampaignRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateCampaignRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Game_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GamePlayer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GamePlayer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuizQuestion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuizQuestion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllGameTypesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllGameTypesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllGameTypesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllGameTypesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGameTypeByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGameTypeByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGameTypeByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGameTypeByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddGameTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddGameTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddGameTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddGameTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateGameTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateGameTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateGameTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateGameTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteGameTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteGameTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteGameTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteGameTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllGamesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllGamesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllGamesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllGamesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGamesByCampaignRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGamesByCampaignRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGamesByCampaignResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGamesByCampaignResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGameByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGameByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGameByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGameByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddGamePlayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddGamePlayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddGamePlayerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddGamePlayerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HasWinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HasWinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HasWinResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HasWinResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetWinItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetWinItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetWinItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetWinItemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetQuizQuestionByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetQuizQuestionByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetQuizQuestionByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetQuizQuestionByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetQuizQuestionsByGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetQuizQuestionsByGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetQuizQuestionsByGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetQuizQuestionsByGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddQuizQuestionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddQuizQuestionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddQuizQuestionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddQuizQuestionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateQuizQuestionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateQuizQuestionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateQuizQuestionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateQuizQuestionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteQuizQuestionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteQuizQuestionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteQuizQuestionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteQuizQuestionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferGameTurnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransferGameTurnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferGameTurnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransferGameTurnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGameTurnsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGameTurnsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGameTurnsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGameTurnsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferPieceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransferPieceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferPieceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransferPieceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllPiecePlayersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllPiecePlayersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllPiecePlayersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllPiecePlayersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePiecePlayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePiecePlayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePiecePlayerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePiecePlayerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRandomPieceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRandomPieceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRandomPieceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRandomPieceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletePieceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletePieceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletePieceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletePieceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePieceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePieceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePieceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePieceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePieceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePieceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePieceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePieceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Piece_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Piece_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPieceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPieceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPieceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPieceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllPiecesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllPiecesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllPiecesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllPiecesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPuzzleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPuzzleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPuzzleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPuzzleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePuzzleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePuzzleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePuzzleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePuzzleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPuzzlesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPuzzlesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Puzzle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Puzzle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPuzzlesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPuzzlesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostCreatePuzzleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostCreatePuzzleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostCreatePuzzleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostCreatePuzzleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateGameTurnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateGameTurnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateGameTurnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateGameTurnResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncore.proto\032\036google/protobuf/wrappers.p" +
      "roto\"%\n\022GetVoucherTypesReq\022\017\n\007brandId\030\001 " +
      "\001(\003\"8\n\022GetVoucherTypesRes\022\"\n\014voucherType" +
      "s\030\001 \003(\0132\014.VoucherType\"&\n\022GetVouchersRequ" +
      "est\022\020\n\010playerId\030\001 \001(\003\"1\n\023GetVouchersResp" +
      "onse\022\032\n\010vouchers\030\001 \003(\0132\010.Voucher\"\035\n\rSear" +
      "chRequest\022\014\n\004term\030\001 \001(\t\"3\n\025SearchVoucher" +
      "Response\022\032\n\010vouchers\030\001 \003(\0132\010.Voucher\"?\n\031" +
      "SearchVoucherTypeResponse\022\"\n\014voucherType" +
      "s\030\001 \003(\0132\014.VoucherType\"\177\n\007Voucher\022\n\n\002id\030\001" +
      " \001(\003\022\020\n\010issuedAt\030\002 \001(\t\022\023\n\013expiredDate\030\003 " +
      "\001(\t\022\016\n\006status\030\004 \001(\t\022\016\n\006QRCode\030\005 \001(\t\022!\n\013v" +
      "oucherType\030\006 \001(\0132\014.VoucherType\"|\n\024Update" +
      "VoucherTypeReq\022\016\n\006status\030\001 \001(\t\022\023\n\013descri" +
      "ption\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\r\n\005value\030\004 \001(\001" +
      "\022\021\n\tvoucherId\030\005 \001(\003\022\017\n\007brandId\030\006 \001(\003\"@\n\024" +
      "UpdateVoucherTypeRes\022(\n\022updatedVoucherTy" +
      "pe\030\001 \001(\0132\014.VoucherType\"d\n\026GenerateVouche" +
      "rRequest\022\025\n\rvoucherTypeId\030\001 \001(\003\022\020\n\010durat" +
      "ion\030\002 \001(\t\022\017\n\007brandId\030\003 \001(\003\022\020\n\010playerId\030\004" +
      " \001(\003\"\217\001\n\027GenerateVoucherResponse\022\n\n\002id\030\001" +
      " \001(\003\022\020\n\010issuedAt\030\002 \001(\t\022\023\n\013expiredDate\030\003 " +
      "\001(\t\022\016\n\006status\030\004 \001(\t\022\016\n\006QRCode\030\005 \001(\t\022!\n\013v" +
      "oucherType\030\006 \001(\0132\014.VoucherType\"o\n\030Create" +
      "VoucherTypeRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\001\022\020\n\010imageUrl\030\003 \001(\t\022\023\n\013description" +
      "\030\004 \001(\t\022\017\n\007brandId\030\005 \001(\003\">\n\031CreateVoucher" +
      "TypeResponse\022!\n\013voucherType\030\001 \001(\0132\014.Vouc" +
      "herType\"n\n\013VoucherType\022\n\n\002id\030\001 \001(\003\022\014\n\004na" +
      "me\030\002 \001(\t\022\r\n\005value\030\003 \001(\001\022\020\n\010imageUrl\030\004 \001(" +
      "\t\022\023\n\013description\030\005 \001(\t\022\017\n\007brandId\030\006 \001(\003\"" +
      "9\n\023GetCampaignsRequest\022\021\n\tstartDate\030\001 \001(" +
      "\t\022\017\n\007endDate\030\002 \001(\t\"4\n\024GetCampaignsRespon" +
      "se\022\034\n\tcampaigns\030\001 \003(\0132\t.Campaign\"\177\n\010Camp" +
      "aign\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010imageU" +
      "rl\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\021\n\tstartDa" +
      "te\030\005 \001(\t\022\017\n\007endDate\030\006 \001(\t\022\016\n\006status\030\007 \001(" +
      "\t\"%\n\025SearchCampaignRequest\022\014\n\004term\030\001 \001(\t" +
      "\"6\n\026SearchCampaignResponse\022\034\n\tcampaigns\030" +
      "\001 \003(\0132\t.Campaign\"\221\001\n\025CreateCampaignReque" +
      "st\022\014\n\004name\030\001 \001(\t\022\020\n\010imageUrl\030\002 \001(\t\022\021\n\tst" +
      "artDate\030\003 \001(\t\022\017\n\007endDate\030\004 \001(\t\022\016\n\006status" +
      "\030\005 \001(\t\022\017\n\007brandId\030\006 \001(\003\022\023\n\013description\030\007" +
      " \001(\t\"\236\001\n\026CreateCampaignResponse\022\014\n\004name\030" +
      "\001 \001(\t\022\020\n\010imageUrl\030\002 \001(\t\022\021\n\tstartDate\030\003 \001" +
      "(\t\022\017\n\007endDate\030\004 \001(\t\022\016\n\006status\030\005 \001(\t\022\017\n\007b" +
      "randId\030\006 \001(\003\022\023\n\013description\030\007 \001(\t\022\n\n\002id\030" +
      "\010 \001(\003\"+\n\030GetCampaignsByBrandIdReq\022\017\n\007bra" +
      "ndId\030\001 \001(\003\"8\n\030GetCampaignsByBrandIdRes\022\034" +
      "\n\tcampaigns\030\001 \003(\0132\t.Campaign\"\242\001\n\021UpdateC" +
      "ampaignReq\022\022\n\ncampaignId\030\001 \001(\003\022\017\n\007newNam" +
      "e\030\002 \001(\t\022\023\n\013newImageUrl\030\003 \001(\t\022\024\n\014newStart" +
      "Date\030\004 \001(\t\022\022\n\nnewEndDate\030\005 \001(\t\022\021\n\tnewSta" +
      "tus\030\006 \001(\t\022\026\n\016newDescription\030\007 \001(\t\"0\n\021Upd" +
      "ateCampaignRes\022\033\n\010campaign\030\001 \001(\0132\t.Campa" +
      "ign\"_\n\010GameType\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(" +
      "\t\022\022\n\nisRealtime\030\003 \001(\010\022\020\n\010imageUrl\030\004 \001(\t\022" +
      "\023\n\013instruction\030\005 \001(\t\"m\n\004Game\022\n\n\002id\030\001 \001(\003" +
      "\022\033\n\023allowPiecesExchange\030\002 \001(\010\022\017\n\007startAt" +
      "\030\003 \001(\t\022\027\n\004type\030\004 \001(\0132\t.GameType\022\022\n\ncampa" +
      "ignId\030\005 \001(\003\"L\n\nGamePlayer\022\n\n\002id\030\001 \001(\003\022\016\n" +
      "\006gameId\030\002 \001(\003\022\020\n\010playerId\030\003 \001(\003\022\020\n\010playe" +
      "dAt\030\004 \001(\t\"\350\001\n\014QuizQuestion\022\n\n\002id\030\001 \001(\003\022\016" +
      "\n\006gameId\030\002 \001(\003\022\026\n\016questionNumber\030\003 \001(\005\022\025" +
      "\n\rquestionTitle\030\004 \001(\t\022\027\n\017questionContent" +
      "\030\005 \001(\t\022\017\n\007answerA\030\006 \001(\t\022\017\n\007answerB\030\007 \001(\t" +
      "\022\017\n\007answerC\030\010 \001(\t\022\017\n\007answerD\030\t \001(\t\022\025\n\rco" +
      "rrectAnswer\030\n \001(\t\022\031\n\021answerExplanation\030\013" +
      " \001(\t\"I\n\004Item\022\033\n\007voucher\030\001 \001(\0132\010.VoucherH" +
      "\000\022\027\n\005piece\030\002 \001(\0132\006.PieceH\000B\013\n\titem_type\"" +
      "\030\n\026GetAllGameTypesRequest\"7\n\027GetAllGameT" +
      "ypesResponse\022\034\n\tgameTypes\030\001 \003(\0132\t.GameTy" +
      "pe\"$\n\026GetGameTypeByIdRequest\022\n\n\002id\030\001 \001(\005" +
      "\"6\n\027GetGameTypeByIdResponse\022\033\n\010gameType\030" +
      "\001 \001(\0132\t.GameType\"]\n\022AddGameTypeRequest\022\014" +
      "\n\004name\030\001 \001(\t\022\022\n\nisRealtime\030\002 \001(\010\022\020\n\010imag" +
      "eUrl\030\003 \001(\t\022\023\n\013instruction\030\004 \001(\t\"2\n\023AddGa" +
      "meTypeResponse\022\033\n\010gameType\030\001 \001(\0132\t.GameT" +
      "ype\"l\n\025UpdateGameTypeRequest\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\022\n\nisRealtime\030\003 \001(\010\022\020\n\010im" +
      "ageUrl\030\004 \001(\t\022\023\n\013instruction\030\005 \001(\t\"5\n\026Upd" +
      "ateGameTypeResponse\022\033\n\010gameType\030\001 \001(\0132\t." +
      "GameType\"#\n\025DeleteGameTypeRequest\022\n\n\002id\030" +
      "\001 \001(\005\"\030\n\026DeleteGameTypeResponse\"\024\n\022GetAl" +
      "lGamesRequest\"+\n\023GetAllGamesResponse\022\024\n\005" +
      "games\030\001 \003(\0132\005.Game\"/\n\031GetGamesByCampaign" +
      "Request\022\022\n\ncampaignId\030\001 \001(\003\"2\n\032GetGamesB" +
      "yCampaignResponse\022\024\n\005games\030\001 \003(\0132\005.Game\"" +
      " \n\022GetGameByIdRequest\022\n\n\002id\030\001 \001(\003\"*\n\023Get" +
      "GameByIdResponse\022\023\n\004game\030\001 \001(\0132\005.Game\"f\n" +
      "\016AddGameRequest\022\033\n\023allowPiecesExchange\030\001" +
      " \001(\010\022\017\n\007startAt\030\002 \001(\t\022\022\n\ngameTypeId\030\003 \001(" +
      "\005\022\022\n\ncampaignId\030\004 \001(\003\"&\n\017AddGameResponse" +
      "\022\023\n\004game\030\001 \001(\0132\005.Game\"u\n\021UpdateGameReque" +
      "st\022\n\n\002id\030\001 \001(\003\022\033\n\023allowPiecesExchange\030\002 " +
      "\001(\010\022\017\n\007startAt\030\003 \001(\t\022\022\n\ngameTypeId\030\004 \001(\005" +
      "\022\022\n\ncampaignId\030\005 \001(\003\")\n\022UpdateGameRespon" +
      "se\022\023\n\004game\030\001 \001(\0132\005.Game\"\037\n\021DeleteGameReq" +
      "uest\022\n\n\002id\030\001 \001(\003\"\024\n\022DeleteGameResponse\"8" +
      "\n\024AddGamePlayerRequest\022\016\n\006gameId\030\001 \001(\003\022\020" +
      "\n\010playerId\030\002 \001(\003\"8\n\025AddGamePlayerRespons" +
      "e\022\037\n\ngamePlayer\030\001 \001(\0132\013.GamePlayer\"!\n\rHa" +
      "sWinRequest\022\020\n\010playerId\030\001 \001(\003\"A\n\016HasWinR" +
      "esponse\022\016\n\006status\030\001 \001(\005\022\017\n\007message\030\002 \001(\t" +
      "\022\016\n\006hasWin\030\003 \001(\010\"5\n\021GetWinItemRequest\022\020\n" +
      "\010playerId\030\001 \001(\003\022\016\n\006gameId\030\002 \001(\003\"J\n\022GetWi" +
      "nItemResponse\022\016\n\006status\030\001 \001(\005\022\017\n\007message" +
      "\030\002 \001(\t\022\023\n\004item\030\003 \001(\0132\005.Item\"(\n\032GetQuizQu" +
      "estionByIdRequest\022\n\n\002id\030\001 \001(\003\"B\n\033GetQuiz" +
      "QuestionByIdResponse\022#\n\014quizQuestion\030\001 \001" +
      "(\0132\r.QuizQuestion\"/\n\035GetQuizQuestionsByG" +
      "ameRequest\022\016\n\006gameId\030\001 \001(\003\"E\n\036GetQuizQue" +
      "stionsByGameResponse\022#\n\014quizQuestion\030\001 \003" +
      "(\0132\r.QuizQuestion\"\346\001\n\026AddQuizQuestionReq" +
      "uest\022\016\n\006gameId\030\001 \001(\003\022\026\n\016questionNumber\030\002" +
      " \001(\005\022\025\n\rquestionTitle\030\003 \001(\t\022\027\n\017questionC" +
      "ontent\030\004 \001(\t\022\017\n\007answerA\030\005 \001(\t\022\017\n\007answerB" +
      "\030\006 \001(\t\022\017\n\007answerC\030\007 \001(\t\022\017\n\007answerD\030\010 \001(\t" +
      "\022\025\n\rcorrectAnswer\030\t \001(\t\022\031\n\021answerExplana" +
      "tion\030\n \001(\t\">\n\027AddQuizQuestionResponse\022#\n" +
      "\014quizQuestion\030\001 \001(\0132\r.QuizQuestion\"\365\001\n\031U" +
      "pdateQuizQuestionRequest\022\n\n\002id\030\001 \001(\003\022\016\n\006" +
      "gameId\030\002 \001(\003\022\026\n\016questionNumber\030\003 \001(\005\022\025\n\r" +
      "questionTitle\030\004 \001(\t\022\027\n\017questionContent\030\005" +
      " \001(\t\022\017\n\007answerA\030\006 \001(\t\022\017\n\007answerB\030\007 \001(\t\022\017" +
      "\n\007answerC\030\010 \001(\t\022\017\n\007answerD\030\t \001(\t\022\025\n\rcorr" +
      "ectAnswer\030\n \001(\t\022\031\n\021answerExplanation\030\013 \001" +
      "(\t\"A\n\032UpdateQuizQuestionResponse\022#\n\014quiz" +
      "Question\030\001 \001(\0132\r.QuizQuestion\"\034\n\032DeleteQ" +
      "uizQuestionResponse\"\'\n\031DeleteQuizQuestio" +
      "nRequest\022\n\n\002id\030\001 \001(\003\"O\n\027TransferGameTurn" +
      "Request\022\020\n\010senderId\030\001 \001(\003\022\023\n\013recipientId" +
      "\030\002 \001(\003\022\r\n\005turns\030\003 \001(\005\";\n\030TransferGameTur" +
      "nResponse\022\016\n\006status\030\001 \001(\003\022\017\n\007message\030\002 \001" +
      "(\t\"\'\n\023GetGameTurnsRequest\022\020\n\010playerId\030\001 " +
      "\001(\003\"F\n\024GetGameTurnsResponse\022\016\n\006status\030\001 " +
      "\001(\003\022\017\n\007message\030\002 \001(\t\022\r\n\005turns\030\003 \001(\005\"N\n\024T" +
      "ransferPieceRequest\022\020\n\010senderId\030\001 \001(\003\022\023\n" +
      "\013recipientId\030\002 \001(\003\022\017\n\007pieceId\030\003 \001(\003\"8\n\025T" +
      "ransferPieceResponse\022\016\n\006status\030\001 \001(\003\022\017\n\007" +
      "message\030\002 \001(\t\"-\n\031GetAllPiecePlayersReque" +
      "st\022\020\n\010playerId\030\001 \001(\003\"T\n\032GetAllPiecePlaye" +
      "rsResponse\022\016\n\006status\030\001 \001(\003\022\017\n\007message\030\002 " +
      "\001(\t\022\025\n\005piece\030\003 \003(\0132\006.Piece\"=\n\030CreatePiec" +
      "ePlayerRequest\022\020\n\010playerId\030\001 \001(\003\022\017\n\007piec" +
      "eId\030\002 \001(\003\"<\n\031CreatePiecePlayerResponse\022\016" +
      "\n\006status\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\")\n\025GetRa" +
      "ndomPieceRequest\022\020\n\010playerId\030\001 \001(\003\"P\n\026Ge" +
      "tRandomPieceResponse\022\016\n\006status\030\001 \001(\003\022\017\n\007" +
      "message\030\002 \001(\t\022\025\n\005piece\030\003 \001(\0132\006.Piece\"7\n\022" +
      "DeletePieceRequest\022\020\n\010puzzleId\030\001 \001(\003\022\017\n\007" +
      "pieceId\030\002 \001(\003\"6\n\023DeletePieceResponse\022\016\n\006" +
      "status\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\"\301\001\n\022Update" +
      "PieceRequest\022\020\n\010puzzleId\030\001 \001(\003\022\017\n\007pieceI" +
      "d\030\002 \001(\003\022+\n\005image\030\003 \001(\0132\034.google.protobuf" +
      ".StringValue\022,\n\007ordinal\030\004 \001(\0132\033.google.p" +
      "rotobuf.Int32Value\022-\n\010quantity\030\005 \001(\0132\033.g" +
      "oogle.protobuf.Int32Value\"6\n\023UpdatePiece" +
      "Response\022\016\n\006status\030\001 \001(\003\022\017\n\007message\030\002 \001(" +
      "\t\"X\n\022CreatePieceRequest\022\r\n\005image\030\001 \001(\t\022\020" +
      "\n\010puzzleId\030\002 \001(\003\022\017\n\007ordinal\030\003 \001(\005\022\020\n\010qua" +
      "ntity\030\004 \001(\005\"6\n\023CreatePieceResponse\022\016\n\006st" +
      "atus\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\"W\n\005Piece\022\n\n\002" +
      "id\030\001 \001(\003\022\r\n\005image\030\002 \001(\t\022\017\n\007ordinal\030\003 \001(\005" +
      "\022\020\n\010puzzleId\030\004 \001(\003\022\020\n\010quantity\030\005 \001(\005\"4\n\017" +
      "GetPieceRequest\022\020\n\010puzzleId\030\001 \001(\003\022\017\n\007pie" +
      "ceId\030\002 \001(\003\"J\n\020GetPieceResponse\022\016\n\006status" +
      "\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\022\025\n\005piece\030\003 \001(\0132\006" +
      ".Piece\"\'\n\023GetAllPiecesRequest\022\020\n\010puzzleI" +
      "d\030\001 \001(\003\"O\n\024GetAllPiecesResponse\022\016\n\006statu" +
      "s\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\022\026\n\006pieces\030\003 \003(\013" +
      "2\006.Piece\"\036\n\020GetPuzzleRequest\022\n\n\002id\030\001 \001(\003" +
      "\"M\n\021GetPuzzleResponse\022\016\n\006status\030\001 \001(\003\022\017\n" +
      "\007message\030\002 \001(\t\022\027\n\006puzzle\030\003 \001(\0132\007.Puzzle\"" +
      "\276\002\n\023UpdatePuzzleRequest\022\n\n\002id\030\001 \001(\003\022+\n\005t" +
      "itle\030\002 \001(\0132\034.google.protobuf.StringValue" +
      "\022+\n\005image\030\003 \001(\0132\034.google.protobuf.String" +
      "Value\022/\n\tstartDate\030\004 \001(\0132\034.google.protob" +
      "uf.StringValue\022-\n\007endDate\030\005 \001(\0132\034.google" +
      ".protobuf.StringValue\0223\n\016numberOfPieces\030" +
      "\006 \001(\0132\033.google.protobuf.Int32Value\022,\n\006st" +
      "atus\030\007 \001(\0132\034.google.protobuf.StringValue" +
      "\"7\n\024UpdatePuzzleResponse\022\016\n\006status\030\001 \001(\003" +
      "\022\017\n\007message\030\002 \001(\t\"\210\001\n\021GetPuzzlesRequest\022" +
      "\014\n\004page\030\001 \001(\005\022\014\n\004size\030\002 \001(\005\022*\n\004sort\030\003 \001(" +
      "\0132\034.google.protobuf.StringValue\022+\n\005title" +
      "\030\004 \001(\0132\034.google.protobuf.StringValue\"~\n\006" +
      "Puzzle\022\n\n\002id\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\r\n\005ima" +
      "ge\030\003 \001(\t\022\021\n\tstartDate\030\004 \001(\t\022\017\n\007endDate\030\005" +
      " \001(\t\022\026\n\016numberOfPieces\030\006 \001(\005\022\016\n\006status\030\007" +
      " \001(\t\"\223\001\n\022GetPuzzlesResponse\022\016\n\006status\030\001 " +
      "\001(\003\022\017\n\007message\030\002 \001(\t\022\021\n\ttotalPage\030\003 \001(\003\022" +
      "\024\n\014totalElement\030\004 \001(\003\022\014\n\004page\030\005 \001(\003\022\014\n\004s" +
      "ize\030\006 \001(\003\022\027\n\006puzzle\030\007 \003(\0132\007.Puzzle\"\203\001\n\027P" +
      "ostCreatePuzzleRequest\022\r\n\005title\030\001 \001(\t\022\r\n" +
      "\005image\030\002 \001(\t\022\021\n\tstartDate\030\003 \001(\t\022\017\n\007endDa" +
      "te\030\004 \001(\t\022\026\n\016numberOfPieces\030\005 \001(\005\022\016\n\006stat" +
      "us\030\006 \001(\t\";\n\030PostCreatePuzzleResponse\022\016\n\006" +
      "status\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\")\n\025CreateG" +
      "ameTurnRequest\022\020\n\010playerId\030\001 \001(\003\"9\n\026Crea" +
      "teGameTurnResponse\022\016\n\006status\030\001 \001(\003\022\017\n\007me" +
      "ssage\030\002 \001(\t2\342\026\n\013CoreService\022D\n\017GenerateV" +
      "oucher\022\027.GenerateVoucherRequest\032\030.Genera" +
      "teVoucherResponse\022J\n\021CreateVoucherType\022\031" +
      ".CreateVoucherTypeRequest\032\032.CreateVouche" +
      "rTypeResponse\0227\n\rSearchVoucher\022\016.SearchR" +
      "equest\032\026.SearchVoucherResponse\022?\n\021Search" +
      "VoucherType\022\016.SearchRequest\032\032.SearchVouc" +
      "herTypeResponse\022A\n\021UpdateVoucherType\022\025.U" +
      "pdateVoucherTypeReq\032\025.UpdateVoucherTypeR" +
      "es\022;\n\017GetVouchersType\022\023.GetVoucherTypesR" +
      "eq\032\023.GetVoucherTypesRes\0228\n\013GetVouchers\022\023" +
      ".GetVouchersRequest\032\024.GetVouchersRespons" +
      "e\022;\n\014GetCampaigns\022\024.GetCampaignsRequest\032" +
      "\025.GetCampaignsResponse\022A\n\016SearchCampaign" +
      "\022\026.SearchCampaignRequest\032\027.SearchCampaig" +
      "nResponse\022A\n\016CreateCampaign\022\026.CreateCamp" +
      "aignRequest\032\027.CreateCampaignResponse\022M\n\025" +
      "GetCampaignsByBrandId\022\031.GetCampaignsByBr" +
      "andIdReq\032\031.GetCampaignsByBrandIdRes\0228\n\016U" +
      "pdateCampaign\022\022.UpdateCampaignReq\032\022.Upda" +
      "teCampaignRes\022D\n\017GetAllGameTypes\022\027.GetAl" +
      "lGameTypesRequest\032\030.GetAllGameTypesRespo" +
      "nse\022D\n\017GetGameTypeById\022\027.GetGameTypeById" +
      "Request\032\030.GetGameTypeByIdResponse\0228\n\013Add" +
      "GameType\022\023.AddGameTypeRequest\032\024.AddGameT" +
      "ypeResponse\022A\n\016UpdateGameType\022\026.UpdateGa" +
      "meTypeRequest\032\027.UpdateGameTypeResponse\022A" +
      "\n\016DeleteGameType\022\026.DeleteGameTypeRequest" +
      "\032\027.DeleteGameTypeResponse\0228\n\013GetAllGames" +
      "\022\023.GetAllGamesRequest\032\024.GetAllGamesRespo" +
      "nse\0228\n\013GetGameById\022\023.GetGameByIdRequest\032" +
      "\024.GetGameByIdResponse\022M\n\022GetGamesByCampa" +
      "ign\022\032.GetGamesByCampaignRequest\032\033.GetGam" +
      "esByCampaignResponse\022,\n\007AddGame\022\017.AddGam" +
      "eRequest\032\020.AddGameResponse\0225\n\nUpdateGame" +
      "\022\022.UpdateGameRequest\032\023.UpdateGameRespons" +
      "e\0225\n\nDeleteGame\022\022.DeleteGameRequest\032\023.De" +
      "leteGameResponse\022>\n\rAddGamePlayer\022\025.AddG" +
      "amePlayerRequest\032\026.AddGamePlayerResponse" +
      "\022)\n\006HasWin\022\016.HasWinRequest\032\017.HasWinRespo" +
      "nse\0225\n\nGetWinItem\022\022.GetWinItemRequest\032\023." +
      "GetWinItemResponse\022P\n\023GetQuizQuestionByI" +
      "d\022\033.GetQuizQuestionByIdRequest\032\034.GetQuiz" +
      "QuestionByIdResponse\022Y\n\026GetQuizQuestions" +
      "ByGame\022\036.GetQuizQuestionsByGameRequest\032\037" +
      ".GetQuizQuestionsByGameResponse\022D\n\017AddQu" +
      "izQuestion\022\027.AddQuizQuestionRequest\032\030.Ad" +
      "dQuizQuestionResponse\022M\n\022UpdateQuizQuest" +
      "ion\022\032.UpdateQuizQuestionRequest\032\033.Update" +
      "QuizQuestionResponse\022M\n\022DeleteQuizQuesti" +
      "on\022\032.DeleteQuizQuestionRequest\032\033.DeleteQ" +
      "uizQuestionResponse\022G\n\020PostCreatePuzzle\022" +
      "\030.PostCreatePuzzleRequest\032\031.PostCreatePu" +
      "zzleResponse\0222\n\tGetPuzzle\022\021.GetPuzzleReq" +
      "uest\032\022.GetPuzzleResponse\0225\n\nGetPuzzles\022\022" +
      ".GetPuzzlesRequest\032\023.GetPuzzlesResponse\022" +
      ";\n\014UpdatePuzzle\022\024.UpdatePuzzleRequest\032\025." +
      "UpdatePuzzleResponse\0228\n\013CreatePiece\022\023.Cr" +
      "eatePieceRequest\032\024.CreatePieceResponse\022/" +
      "\n\010GetPiece\022\020.GetPieceRequest\032\021.GetPieceR" +
      "esponse\0228\n\013UpdatePiece\022\023.UpdatePieceRequ" +
      "est\032\024.UpdatePieceResponse\0228\n\013DeletePiece" +
      "\022\023.DeletePieceRequest\032\024.DeletePieceRespo" +
      "nse\022;\n\014GetAllPieces\022\024.GetAllPiecesReques" +
      "t\032\025.GetAllPiecesResponse\022M\n\022GetAllPieceP" +
      "layers\022\032.GetAllPiecePlayersRequest\032\033.Get" +
      "AllPiecePlayersResponse\022>\n\rTransferPiece" +
      "\022\025.TransferPieceRequest\032\026.TransferPieceR" +
      "esponse\022;\n\014GetGameTurns\022\024.GetGameTurnsRe" +
      "quest\032\025.GetGameTurnsResponse\022G\n\020Transfer" +
      "GameTurn\022\030.TransferGameTurnRequest\032\031.Tra" +
      "nsferGameTurnResponse\022A\n\016CreateGameTurn\022" +
      "\026.CreateGameTurnRequest\032\027.CreateGameTurn" +
      "ResponseB$\n\025org.archi.common.coreB\tCoreP" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_GetVoucherTypesReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetVoucherTypesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVoucherTypesReq_descriptor,
        new java.lang.String[] { "BrandId", });
    internal_static_GetVoucherTypesRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetVoucherTypesRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVoucherTypesRes_descriptor,
        new java.lang.String[] { "VoucherTypes", });
    internal_static_GetVouchersRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetVouchersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVouchersRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_GetVouchersResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetVouchersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVouchersResponse_descriptor,
        new java.lang.String[] { "Vouchers", });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Term", });
    internal_static_SearchVoucherResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SearchVoucherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchVoucherResponse_descriptor,
        new java.lang.String[] { "Vouchers", });
    internal_static_SearchVoucherTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SearchVoucherTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchVoucherTypeResponse_descriptor,
        new java.lang.String[] { "VoucherTypes", });
    internal_static_Voucher_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Voucher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Voucher_descriptor,
        new java.lang.String[] { "Id", "IssuedAt", "ExpiredDate", "Status", "QRCode", "VoucherType", });
    internal_static_UpdateVoucherTypeReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateVoucherTypeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateVoucherTypeReq_descriptor,
        new java.lang.String[] { "Status", "Description", "Name", "Value", "VoucherId", "BrandId", });
    internal_static_UpdateVoucherTypeRes_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateVoucherTypeRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateVoucherTypeRes_descriptor,
        new java.lang.String[] { "UpdatedVoucherType", });
    internal_static_GenerateVoucherRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_GenerateVoucherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateVoucherRequest_descriptor,
        new java.lang.String[] { "VoucherTypeId", "Duration", "BrandId", "PlayerId", });
    internal_static_GenerateVoucherResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GenerateVoucherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateVoucherResponse_descriptor,
        new java.lang.String[] { "Id", "IssuedAt", "ExpiredDate", "Status", "QRCode", "VoucherType", });
    internal_static_CreateVoucherTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_CreateVoucherTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateVoucherTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Value", "ImageUrl", "Description", "BrandId", });
    internal_static_CreateVoucherTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_CreateVoucherTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateVoucherTypeResponse_descriptor,
        new java.lang.String[] { "VoucherType", });
    internal_static_VoucherType_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_VoucherType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoucherType_descriptor,
        new java.lang.String[] { "Id", "Name", "Value", "ImageUrl", "Description", "BrandId", });
    internal_static_GetCampaignsRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_GetCampaignsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsRequest_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", });
    internal_static_GetCampaignsResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_GetCampaignsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsResponse_descriptor,
        new java.lang.String[] { "Campaigns", });
    internal_static_Campaign_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Campaign_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Campaign_descriptor,
        new java.lang.String[] { "Id", "Name", "ImageUrl", "Description", "StartDate", "EndDate", "Status", });
    internal_static_SearchCampaignRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_SearchCampaignRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchCampaignRequest_descriptor,
        new java.lang.String[] { "Term", });
    internal_static_SearchCampaignResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_SearchCampaignResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchCampaignResponse_descriptor,
        new java.lang.String[] { "Campaigns", });
    internal_static_CreateCampaignRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_CreateCampaignRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateCampaignRequest_descriptor,
        new java.lang.String[] { "Name", "ImageUrl", "StartDate", "EndDate", "Status", "BrandId", "Description", });
    internal_static_CreateCampaignResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_CreateCampaignResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateCampaignResponse_descriptor,
        new java.lang.String[] { "Name", "ImageUrl", "StartDate", "EndDate", "Status", "BrandId", "Description", "Id", });
    internal_static_GetCampaignsByBrandIdReq_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_GetCampaignsByBrandIdReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsByBrandIdReq_descriptor,
        new java.lang.String[] { "BrandId", });
    internal_static_GetCampaignsByBrandIdRes_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_GetCampaignsByBrandIdRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsByBrandIdRes_descriptor,
        new java.lang.String[] { "Campaigns", });
    internal_static_UpdateCampaignReq_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_UpdateCampaignReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateCampaignReq_descriptor,
        new java.lang.String[] { "CampaignId", "NewName", "NewImageUrl", "NewStartDate", "NewEndDate", "NewStatus", "NewDescription", });
    internal_static_UpdateCampaignRes_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_UpdateCampaignRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateCampaignRes_descriptor,
        new java.lang.String[] { "Campaign", });
    internal_static_GameType_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_GameType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameType_descriptor,
        new java.lang.String[] { "Id", "Name", "IsRealtime", "ImageUrl", "Instruction", });
    internal_static_Game_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Game_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Game_descriptor,
        new java.lang.String[] { "Id", "AllowPiecesExchange", "StartAt", "Type", "CampaignId", });
    internal_static_GamePlayer_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_GamePlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GamePlayer_descriptor,
        new java.lang.String[] { "Id", "GameId", "PlayerId", "PlayedAt", });
    internal_static_QuizQuestion_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_QuizQuestion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuizQuestion_descriptor,
        new java.lang.String[] { "Id", "GameId", "QuestionNumber", "QuestionTitle", "QuestionContent", "AnswerA", "AnswerB", "AnswerC", "AnswerD", "CorrectAnswer", "AnswerExplanation", });
    internal_static_Item_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Item_descriptor,
        new java.lang.String[] { "Voucher", "Piece", "ItemType", });
    internal_static_GetAllGameTypesRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_GetAllGameTypesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllGameTypesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllGameTypesResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_GetAllGameTypesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllGameTypesResponse_descriptor,
        new java.lang.String[] { "GameTypes", });
    internal_static_GetGameTypeByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_GetGameTypeByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGameTypeByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetGameTypeByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_GetGameTypeByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGameTypeByIdResponse_descriptor,
        new java.lang.String[] { "GameType", });
    internal_static_AddGameTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_AddGameTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddGameTypeRequest_descriptor,
        new java.lang.String[] { "Name", "IsRealtime", "ImageUrl", "Instruction", });
    internal_static_AddGameTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_AddGameTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddGameTypeResponse_descriptor,
        new java.lang.String[] { "GameType", });
    internal_static_UpdateGameTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_UpdateGameTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateGameTypeRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "IsRealtime", "ImageUrl", "Instruction", });
    internal_static_UpdateGameTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_UpdateGameTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateGameTypeResponse_descriptor,
        new java.lang.String[] { "GameType", });
    internal_static_DeleteGameTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_DeleteGameTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteGameTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteGameTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_DeleteGameTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteGameTypeResponse_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllGamesRequest_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_GetAllGamesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllGamesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllGamesResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_GetAllGamesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllGamesResponse_descriptor,
        new java.lang.String[] { "Games", });
    internal_static_GetGamesByCampaignRequest_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_GetGamesByCampaignRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGamesByCampaignRequest_descriptor,
        new java.lang.String[] { "CampaignId", });
    internal_static_GetGamesByCampaignResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_GetGamesByCampaignResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGamesByCampaignResponse_descriptor,
        new java.lang.String[] { "Games", });
    internal_static_GetGameByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_GetGameByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGameByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetGameByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_GetGameByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGameByIdResponse_descriptor,
        new java.lang.String[] { "Game", });
    internal_static_AddGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_AddGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddGameRequest_descriptor,
        new java.lang.String[] { "AllowPiecesExchange", "StartAt", "GameTypeId", "CampaignId", });
    internal_static_AddGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_AddGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddGameResponse_descriptor,
        new java.lang.String[] { "Game", });
    internal_static_UpdateGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_UpdateGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateGameRequest_descriptor,
        new java.lang.String[] { "Id", "AllowPiecesExchange", "StartAt", "GameTypeId", "CampaignId", });
    internal_static_UpdateGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_UpdateGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateGameResponse_descriptor,
        new java.lang.String[] { "Game", });
    internal_static_DeleteGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_DeleteGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteGameRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_DeleteGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteGameResponse_descriptor,
        new java.lang.String[] { });
    internal_static_AddGamePlayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_AddGamePlayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddGamePlayerRequest_descriptor,
        new java.lang.String[] { "GameId", "PlayerId", });
    internal_static_AddGamePlayerResponse_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_AddGamePlayerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddGamePlayerResponse_descriptor,
        new java.lang.String[] { "GamePlayer", });
    internal_static_HasWinRequest_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_HasWinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HasWinRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_HasWinResponse_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_HasWinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HasWinResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "HasWin", });
    internal_static_GetWinItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_GetWinItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetWinItemRequest_descriptor,
        new java.lang.String[] { "PlayerId", "GameId", });
    internal_static_GetWinItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_GetWinItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetWinItemResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Item", });
    internal_static_GetQuizQuestionByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_GetQuizQuestionByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetQuizQuestionByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetQuizQuestionByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_GetQuizQuestionByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetQuizQuestionByIdResponse_descriptor,
        new java.lang.String[] { "QuizQuestion", });
    internal_static_GetQuizQuestionsByGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_GetQuizQuestionsByGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetQuizQuestionsByGameRequest_descriptor,
        new java.lang.String[] { "GameId", });
    internal_static_GetQuizQuestionsByGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_GetQuizQuestionsByGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetQuizQuestionsByGameResponse_descriptor,
        new java.lang.String[] { "QuizQuestion", });
    internal_static_AddQuizQuestionRequest_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_AddQuizQuestionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddQuizQuestionRequest_descriptor,
        new java.lang.String[] { "GameId", "QuestionNumber", "QuestionTitle", "QuestionContent", "AnswerA", "AnswerB", "AnswerC", "AnswerD", "CorrectAnswer", "AnswerExplanation", });
    internal_static_AddQuizQuestionResponse_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_AddQuizQuestionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddQuizQuestionResponse_descriptor,
        new java.lang.String[] { "QuizQuestion", });
    internal_static_UpdateQuizQuestionRequest_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_UpdateQuizQuestionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateQuizQuestionRequest_descriptor,
        new java.lang.String[] { "Id", "GameId", "QuestionNumber", "QuestionTitle", "QuestionContent", "AnswerA", "AnswerB", "AnswerC", "AnswerD", "CorrectAnswer", "AnswerExplanation", });
    internal_static_UpdateQuizQuestionResponse_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_UpdateQuizQuestionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateQuizQuestionResponse_descriptor,
        new java.lang.String[] { "QuizQuestion", });
    internal_static_DeleteQuizQuestionResponse_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_DeleteQuizQuestionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteQuizQuestionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_DeleteQuizQuestionRequest_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_DeleteQuizQuestionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteQuizQuestionRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_TransferGameTurnRequest_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_TransferGameTurnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransferGameTurnRequest_descriptor,
        new java.lang.String[] { "SenderId", "RecipientId", "Turns", });
    internal_static_TransferGameTurnResponse_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_TransferGameTurnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransferGameTurnResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_GetGameTurnsRequest_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_GetGameTurnsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGameTurnsRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_GetGameTurnsResponse_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_GetGameTurnsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGameTurnsResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Turns", });
    internal_static_TransferPieceRequest_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_TransferPieceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransferPieceRequest_descriptor,
        new java.lang.String[] { "SenderId", "RecipientId", "PieceId", });
    internal_static_TransferPieceResponse_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_TransferPieceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransferPieceResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_GetAllPiecePlayersRequest_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_GetAllPiecePlayersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllPiecePlayersRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_GetAllPiecePlayersResponse_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_GetAllPiecePlayersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllPiecePlayersResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Piece", });
    internal_static_CreatePiecePlayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_CreatePiecePlayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePiecePlayerRequest_descriptor,
        new java.lang.String[] { "PlayerId", "PieceId", });
    internal_static_CreatePiecePlayerResponse_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_CreatePiecePlayerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePiecePlayerResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_GetRandomPieceRequest_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_GetRandomPieceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRandomPieceRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_GetRandomPieceResponse_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_GetRandomPieceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRandomPieceResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Piece", });
    internal_static_DeletePieceRequest_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_DeletePieceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletePieceRequest_descriptor,
        new java.lang.String[] { "PuzzleId", "PieceId", });
    internal_static_DeletePieceResponse_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_DeletePieceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletePieceResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_UpdatePieceRequest_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_UpdatePieceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePieceRequest_descriptor,
        new java.lang.String[] { "PuzzleId", "PieceId", "Image", "Ordinal", "Quantity", });
    internal_static_UpdatePieceResponse_descriptor =
      getDescriptor().getMessageTypes().get(84);
    internal_static_UpdatePieceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePieceResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_CreatePieceRequest_descriptor =
      getDescriptor().getMessageTypes().get(85);
    internal_static_CreatePieceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePieceRequest_descriptor,
        new java.lang.String[] { "Image", "PuzzleId", "Ordinal", "Quantity", });
    internal_static_CreatePieceResponse_descriptor =
      getDescriptor().getMessageTypes().get(86);
    internal_static_CreatePieceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePieceResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_Piece_descriptor =
      getDescriptor().getMessageTypes().get(87);
    internal_static_Piece_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Piece_descriptor,
        new java.lang.String[] { "Id", "Image", "Ordinal", "PuzzleId", "Quantity", });
    internal_static_GetPieceRequest_descriptor =
      getDescriptor().getMessageTypes().get(88);
    internal_static_GetPieceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPieceRequest_descriptor,
        new java.lang.String[] { "PuzzleId", "PieceId", });
    internal_static_GetPieceResponse_descriptor =
      getDescriptor().getMessageTypes().get(89);
    internal_static_GetPieceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPieceResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Piece", });
    internal_static_GetAllPiecesRequest_descriptor =
      getDescriptor().getMessageTypes().get(90);
    internal_static_GetAllPiecesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllPiecesRequest_descriptor,
        new java.lang.String[] { "PuzzleId", });
    internal_static_GetAllPiecesResponse_descriptor =
      getDescriptor().getMessageTypes().get(91);
    internal_static_GetAllPiecesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllPiecesResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Pieces", });
    internal_static_GetPuzzleRequest_descriptor =
      getDescriptor().getMessageTypes().get(92);
    internal_static_GetPuzzleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPuzzleRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetPuzzleResponse_descriptor =
      getDescriptor().getMessageTypes().get(93);
    internal_static_GetPuzzleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPuzzleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Puzzle", });
    internal_static_UpdatePuzzleRequest_descriptor =
      getDescriptor().getMessageTypes().get(94);
    internal_static_UpdatePuzzleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePuzzleRequest_descriptor,
        new java.lang.String[] { "Id", "Title", "Image", "StartDate", "EndDate", "NumberOfPieces", "Status", });
    internal_static_UpdatePuzzleResponse_descriptor =
      getDescriptor().getMessageTypes().get(95);
    internal_static_UpdatePuzzleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePuzzleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_GetPuzzlesRequest_descriptor =
      getDescriptor().getMessageTypes().get(96);
    internal_static_GetPuzzlesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPuzzlesRequest_descriptor,
        new java.lang.String[] { "Page", "Size", "Sort", "Title", });
    internal_static_Puzzle_descriptor =
      getDescriptor().getMessageTypes().get(97);
    internal_static_Puzzle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Puzzle_descriptor,
        new java.lang.String[] { "Id", "Title", "Image", "StartDate", "EndDate", "NumberOfPieces", "Status", });
    internal_static_GetPuzzlesResponse_descriptor =
      getDescriptor().getMessageTypes().get(98);
    internal_static_GetPuzzlesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPuzzlesResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "TotalPage", "TotalElement", "Page", "Size", "Puzzle", });
    internal_static_PostCreatePuzzleRequest_descriptor =
      getDescriptor().getMessageTypes().get(99);
    internal_static_PostCreatePuzzleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostCreatePuzzleRequest_descriptor,
        new java.lang.String[] { "Title", "Image", "StartDate", "EndDate", "NumberOfPieces", "Status", });
    internal_static_PostCreatePuzzleResponse_descriptor =
      getDescriptor().getMessageTypes().get(100);
    internal_static_PostCreatePuzzleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostCreatePuzzleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_CreateGameTurnRequest_descriptor =
      getDescriptor().getMessageTypes().get(101);
    internal_static_CreateGameTurnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateGameTurnRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_CreateGameTurnResponse_descriptor =
      getDescriptor().getMessageTypes().get(102);
    internal_static_CreateGameTurnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateGameTurnResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
