// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

public final class CoreProto {
  private CoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVoucherTypesReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVoucherTypesReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVoucherTypesRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVoucherTypesRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVouchersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVouchersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVouchersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVouchersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchVoucherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchVoucherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchVoucherTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchVoucherTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Voucher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Voucher_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateVoucherTypeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateVoucherTypeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateVoucherTypeRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateVoucherTypeRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateVoucherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateVoucherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateVoucherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateVoucherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateVoucherTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateVoucherTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateVoucherTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateVoucherTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoucherType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoucherType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Campaign_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Campaign_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchCampaignRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchCampaignRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchCampaignResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchCampaignResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateCampaignRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateCampaignRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateCampaignResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateCampaignResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsByBrandIdReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsByBrandIdReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCampaignsByBrandIdRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCampaignsByBrandIdRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateCampaignReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateCampaignReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateCampaignRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateCampaignRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncore.proto\"%\n\022GetVoucherTypesReq\022\017\n\007br" +
      "andId\030\001 \001(\003\"8\n\022GetVoucherTypesRes\022\"\n\014vou" +
      "cherTypes\030\001 \003(\0132\014.VoucherType\"&\n\022GetVouc" +
      "hersRequest\022\020\n\010playerId\030\001 \001(\003\"1\n\023GetVouc" +
      "hersResponse\022\032\n\010vouchers\030\001 \003(\0132\010.Voucher" +
      "\"\035\n\rSearchRequest\022\014\n\004term\030\001 \001(\t\"3\n\025Searc" +
      "hVoucherResponse\022\032\n\010vouchers\030\001 \003(\0132\010.Vou" +
      "cher\"?\n\031SearchVoucherTypeResponse\022\"\n\014vou" +
      "cherTypes\030\001 \003(\0132\014.VoucherType\"\177\n\007Voucher" +
      "\022\n\n\002id\030\001 \001(\003\022\020\n\010issuedAt\030\002 \001(\t\022\023\n\013expire" +
      "dDate\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\022\016\n\006QRCode\030\005 " +
      "\001(\t\022!\n\013voucherType\030\006 \001(\0132\014.VoucherType\"|" +
      "\n\024UpdateVoucherTypeReq\022\016\n\006status\030\001 \001(\t\022\023" +
      "\n\013description\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\r\n\005val" +
      "ue\030\004 \001(\001\022\021\n\tvoucherId\030\005 \001(\003\022\017\n\007brandId\030\006" +
      " \001(\003\"@\n\024UpdateVoucherTypeRes\022(\n\022updatedV" +
      "oucherType\030\001 \001(\0132\014.VoucherType\"d\n\026Genera" +
      "teVoucherRequest\022\025\n\rvoucherTypeId\030\001 \001(\003\022" +
      "\020\n\010duration\030\002 \001(\t\022\017\n\007brandId\030\003 \001(\003\022\020\n\010pl" +
      "ayerId\030\004 \001(\003\"\217\001\n\027GenerateVoucherResponse" +
      "\022\n\n\002id\030\001 \001(\003\022\020\n\010issuedAt\030\002 \001(\t\022\023\n\013expire" +
      "dDate\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\022\016\n\006QRCode\030\005 " +
      "\001(\t\022!\n\013voucherType\030\006 \001(\0132\014.VoucherType\"o" +
      "\n\030CreateVoucherTypeRequest\022\014\n\004name\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\001\022\020\n\010imageUrl\030\003 \001(\t\022\023\n\013des" +
      "cription\030\004 \001(\t\022\017\n\007brandId\030\005 \001(\003\">\n\031Creat" +
      "eVoucherTypeResponse\022!\n\013voucherType\030\001 \001(" +
      "\0132\014.VoucherType\"n\n\013VoucherType\022\n\n\002id\030\001 \001" +
      "(\003\022\014\n\004name\030\002 \001(\t\022\r\n\005value\030\003 \001(\001\022\020\n\010image" +
      "Url\030\004 \001(\t\022\023\n\013description\030\005 \001(\t\022\017\n\007brandI" +
      "d\030\006 \001(\003\"9\n\023GetCampaignsRequest\022\021\n\tstartD" +
      "ate\030\001 \001(\t\022\017\n\007endDate\030\002 \001(\t\"4\n\024GetCampaig" +
      "nsResponse\022\034\n\tcampaigns\030\001 \003(\0132\t.Campaign" +
      "\"\177\n\010Campaign\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020" +
      "\n\010imageUrl\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\021\n" +
      "\tstartDate\030\005 \001(\t\022\017\n\007endDate\030\006 \001(\t\022\016\n\006sta" +
      "tus\030\007 \001(\t\"%\n\025SearchCampaignRequest\022\014\n\004te" +
      "rm\030\001 \001(\t\"6\n\026SearchCampaignResponse\022\034\n\tca" +
      "mpaigns\030\001 \003(\0132\t.Campaign\"\221\001\n\025CreateCampa" +
      "ignRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010imageUrl\030\002 \001" +
      "(\t\022\021\n\tstartDate\030\003 \001(\t\022\017\n\007endDate\030\004 \001(\t\022\016" +
      "\n\006status\030\005 \001(\t\022\017\n\007brandId\030\006 \001(\003\022\023\n\013descr" +
      "iption\030\007 \001(\t\"5\n\026CreateCampaignResponse\022\033" +
      "\n\010campaign\030\001 \001(\0132\t.Campaign\"+\n\030GetCampai" +
      "gnsByBrandIdReq\022\017\n\007brandId\030\001 \001(\003\"8\n\030GetC" +
      "ampaignsByBrandIdRes\022\034\n\tcampaigns\030\001 \003(\0132" +
      "\t.Campaign\"\242\001\n\021UpdateCampaignReq\022\022\n\ncamp" +
      "aignId\030\001 \001(\003\022\017\n\007newName\030\002 \001(\t\022\023\n\013newImag" +
      "eUrl\030\003 \001(\t\022\024\n\014newStartDate\030\004 \001(\t\022\022\n\nnewE" +
      "ndDate\030\005 \001(\t\022\021\n\tnewStatus\030\006 \001(\t\022\026\n\016newDe" +
      "scription\030\007 \001(\t\"0\n\021UpdateCampaignRes\022\033\n\010" +
      "campaign\030\001 \001(\0132\t.Campaign2\237\006\n\013CoreServic" +
      "e\022D\n\017GenerateVoucher\022\027.GenerateVoucherRe" +
      "quest\032\030.GenerateVoucherResponse\022J\n\021Creat" +
      "eVoucherType\022\031.CreateVoucherTypeRequest\032" +
      "\032.CreateVoucherTypeResponse\0227\n\rSearchVou" +
      "cher\022\016.SearchRequest\032\026.SearchVoucherResp" +
      "onse\022?\n\021SearchVoucherType\022\016.SearchReques" +
      "t\032\032.SearchVoucherTypeResponse\022A\n\021UpdateV" +
      "oucherType\022\025.UpdateVoucherTypeReq\032\025.Upda" +
      "teVoucherTypeRes\022;\n\017GetVouchersType\022\023.Ge" +
      "tVoucherTypesReq\032\023.GetVoucherTypesRes\0228\n" +
      "\013GetVouchers\022\023.GetVouchersRequest\032\024.GetV" +
      "ouchersResponse\022;\n\014GetCampaigns\022\024.GetCam" +
      "paignsRequest\032\025.GetCampaignsResponse\022A\n\016" +
      "SearchCampaign\022\026.SearchCampaignRequest\032\027" +
      ".SearchCampaignResponse\022A\n\016CreateCampaig" +
      "n\022\026.CreateCampaignRequest\032\027.CreateCampai" +
      "gnResponse\022M\n\025GetCampaignsByBrandId\022\031.Ge" +
      "tCampaignsByBrandIdReq\032\031.GetCampaignsByB" +
      "randIdRes\0228\n\016UpdateCampaign\022\022.UpdateCamp" +
      "aignReq\032\022.UpdateCampaignResB$\n\025org.archi" +
      ".common.coreB\tCoreProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetVoucherTypesReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetVoucherTypesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVoucherTypesReq_descriptor,
        new java.lang.String[] { "BrandId", });
    internal_static_GetVoucherTypesRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetVoucherTypesRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVoucherTypesRes_descriptor,
        new java.lang.String[] { "VoucherTypes", });
    internal_static_GetVouchersRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetVouchersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVouchersRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_GetVouchersResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetVouchersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVouchersResponse_descriptor,
        new java.lang.String[] { "Vouchers", });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Term", });
    internal_static_SearchVoucherResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SearchVoucherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchVoucherResponse_descriptor,
        new java.lang.String[] { "Vouchers", });
    internal_static_SearchVoucherTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SearchVoucherTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchVoucherTypeResponse_descriptor,
        new java.lang.String[] { "VoucherTypes", });
    internal_static_Voucher_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Voucher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Voucher_descriptor,
        new java.lang.String[] { "Id", "IssuedAt", "ExpiredDate", "Status", "QRCode", "VoucherType", });
    internal_static_UpdateVoucherTypeReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateVoucherTypeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateVoucherTypeReq_descriptor,
        new java.lang.String[] { "Status", "Description", "Name", "Value", "VoucherId", "BrandId", });
    internal_static_UpdateVoucherTypeRes_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateVoucherTypeRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateVoucherTypeRes_descriptor,
        new java.lang.String[] { "UpdatedVoucherType", });
    internal_static_GenerateVoucherRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_GenerateVoucherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateVoucherRequest_descriptor,
        new java.lang.String[] { "VoucherTypeId", "Duration", "BrandId", "PlayerId", });
    internal_static_GenerateVoucherResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GenerateVoucherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateVoucherResponse_descriptor,
        new java.lang.String[] { "Id", "IssuedAt", "ExpiredDate", "Status", "QRCode", "VoucherType", });
    internal_static_CreateVoucherTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_CreateVoucherTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateVoucherTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Value", "ImageUrl", "Description", "BrandId", });
    internal_static_CreateVoucherTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_CreateVoucherTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateVoucherTypeResponse_descriptor,
        new java.lang.String[] { "VoucherType", });
    internal_static_VoucherType_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_VoucherType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoucherType_descriptor,
        new java.lang.String[] { "Id", "Name", "Value", "ImageUrl", "Description", "BrandId", });
    internal_static_GetCampaignsRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_GetCampaignsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsRequest_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", });
    internal_static_GetCampaignsResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_GetCampaignsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsResponse_descriptor,
        new java.lang.String[] { "Campaigns", });
    internal_static_Campaign_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Campaign_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Campaign_descriptor,
        new java.lang.String[] { "Id", "Name", "ImageUrl", "Description", "StartDate", "EndDate", "Status", });
    internal_static_SearchCampaignRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_SearchCampaignRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchCampaignRequest_descriptor,
        new java.lang.String[] { "Term", });
    internal_static_SearchCampaignResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_SearchCampaignResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchCampaignResponse_descriptor,
        new java.lang.String[] { "Campaigns", });
    internal_static_CreateCampaignRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_CreateCampaignRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateCampaignRequest_descriptor,
        new java.lang.String[] { "Name", "ImageUrl", "StartDate", "EndDate", "Status", "BrandId", "Description", });
    internal_static_CreateCampaignResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_CreateCampaignResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateCampaignResponse_descriptor,
        new java.lang.String[] { "Campaign", });
    internal_static_GetCampaignsByBrandIdReq_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_GetCampaignsByBrandIdReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsByBrandIdReq_descriptor,
        new java.lang.String[] { "BrandId", });
    internal_static_GetCampaignsByBrandIdRes_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_GetCampaignsByBrandIdRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCampaignsByBrandIdRes_descriptor,
        new java.lang.String[] { "Campaigns", });
    internal_static_UpdateCampaignReq_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_UpdateCampaignReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateCampaignReq_descriptor,
        new java.lang.String[] { "CampaignId", "NewName", "NewImageUrl", "NewStartDate", "NewEndDate", "NewStatus", "NewDescription", });
    internal_static_UpdateCampaignRes_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_UpdateCampaignRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateCampaignRes_descriptor,
        new java.lang.String[] { "Campaign", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
