// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

/**
 * Protobuf type {@code CreateCampaignResponse}
 */
public final class CreateCampaignResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateCampaignResponse)
    CreateCampaignResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateCampaignResponse.newBuilder() to construct.
  private CreateCampaignResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateCampaignResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateCampaignResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.archi.common.core.CoreProto.internal_static_CreateCampaignResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.archi.common.core.CoreProto.internal_static_CreateCampaignResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.archi.common.core.CreateCampaignResponse.class, org.archi.common.core.CreateCampaignResponse.Builder.class);
  }

  public static final int CAMPAIGN_FIELD_NUMBER = 1;
  private org.archi.common.core.Campaign campaign_;
  /**
   * <code>.Campaign campaign = 1;</code>
   * @return Whether the campaign field is set.
   */
  @java.lang.Override
  public boolean hasCampaign() {
    return campaign_ != null;
  }
  /**
   * <code>.Campaign campaign = 1;</code>
   * @return The campaign.
   */
  @java.lang.Override
  public org.archi.common.core.Campaign getCampaign() {
    return campaign_ == null ? org.archi.common.core.Campaign.getDefaultInstance() : campaign_;
  }
  /**
   * <code>.Campaign campaign = 1;</code>
   */
  @java.lang.Override
  public org.archi.common.core.CampaignOrBuilder getCampaignOrBuilder() {
    return getCampaign();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (campaign_ != null) {
      output.writeMessage(1, getCampaign());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (campaign_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCampaign());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.archi.common.core.CreateCampaignResponse)) {
      return super.equals(obj);
    }
    org.archi.common.core.CreateCampaignResponse other = (org.archi.common.core.CreateCampaignResponse) obj;

    if (hasCampaign() != other.hasCampaign()) return false;
    if (hasCampaign()) {
      if (!getCampaign()
          .equals(other.getCampaign())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCampaign()) {
      hash = (37 * hash) + CAMPAIGN_FIELD_NUMBER;
      hash = (53 * hash) + getCampaign().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.archi.common.core.CreateCampaignResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.archi.common.core.CreateCampaignResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.archi.common.core.CreateCampaignResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.archi.common.core.CreateCampaignResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateCampaignResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateCampaignResponse)
      org.archi.common.core.CreateCampaignResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.archi.common.core.CoreProto.internal_static_CreateCampaignResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.archi.common.core.CoreProto.internal_static_CreateCampaignResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.archi.common.core.CreateCampaignResponse.class, org.archi.common.core.CreateCampaignResponse.Builder.class);
    }

    // Construct using org.archi.common.core.CreateCampaignResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (campaignBuilder_ == null) {
        campaign_ = null;
      } else {
        campaign_ = null;
        campaignBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.archi.common.core.CoreProto.internal_static_CreateCampaignResponse_descriptor;
    }

    @java.lang.Override
    public org.archi.common.core.CreateCampaignResponse getDefaultInstanceForType() {
      return org.archi.common.core.CreateCampaignResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.archi.common.core.CreateCampaignResponse build() {
      org.archi.common.core.CreateCampaignResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.archi.common.core.CreateCampaignResponse buildPartial() {
      org.archi.common.core.CreateCampaignResponse result = new org.archi.common.core.CreateCampaignResponse(this);
      if (campaignBuilder_ == null) {
        result.campaign_ = campaign_;
      } else {
        result.campaign_ = campaignBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.archi.common.core.CreateCampaignResponse) {
        return mergeFrom((org.archi.common.core.CreateCampaignResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.archi.common.core.CreateCampaignResponse other) {
      if (other == org.archi.common.core.CreateCampaignResponse.getDefaultInstance()) return this;
      if (other.hasCampaign()) {
        mergeCampaign(other.getCampaign());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCampaignFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private org.archi.common.core.Campaign campaign_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.archi.common.core.Campaign, org.archi.common.core.Campaign.Builder, org.archi.common.core.CampaignOrBuilder> campaignBuilder_;
    /**
     * <code>.Campaign campaign = 1;</code>
     * @return Whether the campaign field is set.
     */
    public boolean hasCampaign() {
      return campaignBuilder_ != null || campaign_ != null;
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     * @return The campaign.
     */
    public org.archi.common.core.Campaign getCampaign() {
      if (campaignBuilder_ == null) {
        return campaign_ == null ? org.archi.common.core.Campaign.getDefaultInstance() : campaign_;
      } else {
        return campaignBuilder_.getMessage();
      }
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     */
    public Builder setCampaign(org.archi.common.core.Campaign value) {
      if (campaignBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        campaign_ = value;
        onChanged();
      } else {
        campaignBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     */
    public Builder setCampaign(
        org.archi.common.core.Campaign.Builder builderForValue) {
      if (campaignBuilder_ == null) {
        campaign_ = builderForValue.build();
        onChanged();
      } else {
        campaignBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     */
    public Builder mergeCampaign(org.archi.common.core.Campaign value) {
      if (campaignBuilder_ == null) {
        if (campaign_ != null) {
          campaign_ =
            org.archi.common.core.Campaign.newBuilder(campaign_).mergeFrom(value).buildPartial();
        } else {
          campaign_ = value;
        }
        onChanged();
      } else {
        campaignBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     */
    public Builder clearCampaign() {
      if (campaignBuilder_ == null) {
        campaign_ = null;
        onChanged();
      } else {
        campaign_ = null;
        campaignBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     */
    public org.archi.common.core.Campaign.Builder getCampaignBuilder() {
      
      onChanged();
      return getCampaignFieldBuilder().getBuilder();
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     */
    public org.archi.common.core.CampaignOrBuilder getCampaignOrBuilder() {
      if (campaignBuilder_ != null) {
        return campaignBuilder_.getMessageOrBuilder();
      } else {
        return campaign_ == null ?
            org.archi.common.core.Campaign.getDefaultInstance() : campaign_;
      }
    }
    /**
     * <code>.Campaign campaign = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.archi.common.core.Campaign, org.archi.common.core.Campaign.Builder, org.archi.common.core.CampaignOrBuilder> 
        getCampaignFieldBuilder() {
      if (campaignBuilder_ == null) {
        campaignBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.archi.common.core.Campaign, org.archi.common.core.Campaign.Builder, org.archi.common.core.CampaignOrBuilder>(
                getCampaign(),
                getParentForChildren(),
                isClean());
        campaign_ = null;
      }
      return campaignBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreateCampaignResponse)
  }

  // @@protoc_insertion_point(class_scope:CreateCampaignResponse)
  private static final org.archi.common.core.CreateCampaignResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.archi.common.core.CreateCampaignResponse();
  }

  public static org.archi.common.core.CreateCampaignResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateCampaignResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateCampaignResponse>() {
    @java.lang.Override
    public CreateCampaignResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateCampaignResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateCampaignResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.archi.common.core.CreateCampaignResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

