// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

public interface DeletePieceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeletePieceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 puzzleId = 1;</code>
   * @return The puzzleId.
   */
  long getPuzzleId();

  /**
   * <code>int64 pieceId = 2;</code>
   * @return The pieceId.
   */
  long getPieceId();
}
