// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

public interface GetWinItemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetWinItemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.Item item = 3;</code>
   * @return Whether the item field is set.
   */
  boolean hasItem();
  /**
   * <code>.Item item = 3;</code>
   * @return The item.
   */
  org.archi.common.core.Item getItem();
  /**
   * <code>.Item item = 3;</code>
   */
  org.archi.common.core.ItemOrBuilder getItemOrBuilder();
}
