// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

public interface SearchCampaignResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchCampaignResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Campaign campaigns = 1;</code>
   */
  java.util.List<org.archi.common.core.Campaign> 
      getCampaignsList();
  /**
   * <code>repeated .Campaign campaigns = 1;</code>
   */
  org.archi.common.core.Campaign getCampaigns(int index);
  /**
   * <code>repeated .Campaign campaigns = 1;</code>
   */
  int getCampaignsCount();
  /**
   * <code>repeated .Campaign campaigns = 1;</code>
   */
  java.util.List<? extends org.archi.common.core.CampaignOrBuilder> 
      getCampaignsOrBuilderList();
  /**
   * <code>repeated .Campaign campaigns = 1;</code>
   */
  org.archi.common.core.CampaignOrBuilder getCampaignsOrBuilder(
      int index);
}
