// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

public interface SearchVoucherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchVoucherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Voucher vouchers = 1;</code>
   */
  java.util.List<org.archi.common.core.Voucher> 
      getVouchersList();
  /**
   * <code>repeated .Voucher vouchers = 1;</code>
   */
  org.archi.common.core.Voucher getVouchers(int index);
  /**
   * <code>repeated .Voucher vouchers = 1;</code>
   */
  int getVouchersCount();
  /**
   * <code>repeated .Voucher vouchers = 1;</code>
   */
  java.util.List<? extends org.archi.common.core.VoucherOrBuilder> 
      getVouchersOrBuilderList();
  /**
   * <code>repeated .Voucher vouchers = 1;</code>
   */
  org.archi.common.core.VoucherOrBuilder getVouchersOrBuilder(
      int index);
}
