// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package org.archi.common.core;

public interface UpdatePuzzleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdatePuzzleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.google.protobuf.StringValue title = 2;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>.google.protobuf.StringValue title = 2;</code>
   * @return The title.
   */
  com.google.protobuf.StringValue getTitle();
  /**
   * <code>.google.protobuf.StringValue title = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTitleOrBuilder();

  /**
   * <code>.google.protobuf.StringValue image = 3;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>.google.protobuf.StringValue image = 3;</code>
   * @return The image.
   */
  com.google.protobuf.StringValue getImage();
  /**
   * <code>.google.protobuf.StringValue image = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getImageOrBuilder();

  /**
   * <code>.google.protobuf.StringValue startDate = 4;</code>
   * @return Whether the startDate field is set.
   */
  boolean hasStartDate();
  /**
   * <code>.google.protobuf.StringValue startDate = 4;</code>
   * @return The startDate.
   */
  com.google.protobuf.StringValue getStartDate();
  /**
   * <code>.google.protobuf.StringValue startDate = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getStartDateOrBuilder();

  /**
   * <code>.google.protobuf.StringValue endDate = 5;</code>
   * @return Whether the endDate field is set.
   */
  boolean hasEndDate();
  /**
   * <code>.google.protobuf.StringValue endDate = 5;</code>
   * @return The endDate.
   */
  com.google.protobuf.StringValue getEndDate();
  /**
   * <code>.google.protobuf.StringValue endDate = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getEndDateOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value numberOfPieces = 6;</code>
   * @return Whether the numberOfPieces field is set.
   */
  boolean hasNumberOfPieces();
  /**
   * <code>.google.protobuf.Int32Value numberOfPieces = 6;</code>
   * @return The numberOfPieces.
   */
  com.google.protobuf.Int32Value getNumberOfPieces();
  /**
   * <code>.google.protobuf.Int32Value numberOfPieces = 6;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getNumberOfPiecesOrBuilder();

  /**
   * <code>.google.protobuf.StringValue status = 7;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.google.protobuf.StringValue status = 7;</code>
   * @return The status.
   */
  com.google.protobuf.StringValue getStatus();
  /**
   * <code>.google.protobuf.StringValue status = 7;</code>
   */
  com.google.protobuf.StringValueOrBuilder getStatusOrBuilder();
}
